language: python
python:
  - "2.7"

env:
  global:
    # for $TENDENCI_TRANSIFEX_PASSWORD
    secure: "KhPHO/DbtBkuvZuT78iC5hEaZQxKN/v1/lsXA+Shxxd2k8tUPKjYRhGDPM+qZm6/j1vMMi7IA/fVBRwV4X6XkljH+p8fzo5er7Q/nFNmmB9IbpQ8j44X1fmkCSbOTsIxhgFBmHmIrdpNducA26QrKDV3GUaV13kQTdk9cxvFIiY="

# command to install dependencies
install:
  - pip install Django==1.4.13

# TODO: command to run tests
# for now, run command to push source and translation files to Transifex
script: ./transifex.sh
